version: '3'
services:
  redis5:
    container_name: redis5
    image: redis:5.0.6
    ports:
      - '127.0.0.1:6379:6379'
    volumes:
      - ./docker/data/redis:/data

  redis-rb-benchmark:
    container_name: benchmark
    build: ./docker/benchmark
    depends_on:
      - redis5
    volumes:
      - ./docker/benchmark:/app
      - bundle:/usr/local/bundle:cached
    command: ruby benchmark.rb

volumes:
  bundle:
    driver: local
